### ISSUE TITLE
can't install via pip

### ISSUE THREAD

**Issue by the-ivan** [davehunt/PyPOM#5]
Hey Dave!

A brief issue I noticed is that I can't install via command: `pip install PyPOM`

>Could not find a version that satisfies the requirement PyPOM (from versions: )
>No matching distribution found for PyPOM

Could you explain what's causing this?

**Comment by davehunt** [comment]
Hey @the-ivan it's not released yet. You can install it by allowing pre-releases to be installed, but I don't recommend it as there are still API changes happening.

**Comment by davehunt** [comment]
From `pip install --help`:

> --pre                       Include pre-release and development versions. By default, pip only finds stable versions.
